name: musiclassification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.20
  - pip
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - tensorflow-gpu
  - numpy=1.23.5
  - matplotlib=3.5.3
  - pandas
  - scipy
  - scikit-learn=1.2.2
  - librosa=0.11.0
  - PyQt6=6.7.1
  - pip:
      - soundfile==0.13.1
      - tqdm
      - resampy
      - soxr
      - msgpack==1.1.0
      - joblib==1.4.2
      - colorama
      - requests==2.32.3
      - charset-normalizer==3.4.1
      - idna==3.10
      - urllib3
      - certifi==2025.1.31

